name: Test Runner

on: push

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current folder
        run: pwd

      - name: List files
        run: ls -la

      - name: Show current user
        run: whoami

      - name: Show docker version
        run: docker version
